import Head from 'next/head'
import Image from 'next/image'
import { UploadButton } from '../components/uploadButton'
import styles from '../styles/Home.module.css'
import { server } from '../config'
import { ColorCard } from '../components/colorCard'

export default function Home({colors}) {
  console.log(colors.result)
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaler Palets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Get a <span className={styles.colored}>Color Palette</span> from an Image 
        </h1>

        <p className={styles.description}>
          Get started by uploading a picture
        </p>
        <UploadButton/>
        <div className={styles.palette}>
          {
            colors.result.map((field,index)=><ColorCard key={index} colorArray={field} />)
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Eeesaaarr
        </a>
      </footer>
    </div>
  )
}


export const getStaticProps= async()=>{
  const res =await fetch(`${server}/api/colors`)
  const colors=await res.json()

  return{
    props:{
      colors
    }

  }
}